function Hd = FIR_Bandpass_Toolbox_HammingWin
%FIR_BANDPASS_TOOLBOX_HAMMINGWIN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 27-Jun-2017 14:38:41

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 256;  % Sampling Frequency

N    = 30;       % Order
Fc1  = 50;       % First Cutoff Frequency
Fc2  = 125;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
