function Hd = FIR_Bandstop_Toolbox_HammingWin
%FIR_BANDSTOP_TOOLBOX Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 27-Jun-2017 14:25:48

% FIR Window Bandstop filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 256;  % Sampling Frequency

N    = 30;       % Order
Fc1  = 55;       % First Cutoff Frequency
Fc2  = 65;       % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'stop', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
