function Hd = FIR_Bandpass_Toolbox_BlackmanWin
%FIR_BANDPASS_TOOLBOX_BLACKMANWIN Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 10-Jul-2017 19:40:52

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 256;  % Sampling Frequency

N    = 10;       % Order
Fc1  = 50;       % First Cutoff Frequency
Fc2  = 125;      % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag
% Create the window vector for the design algorithm.
win = blackman(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
Hd = dsp.FIRFilter( ...
    'Numerator', b);

% [EOF]
